//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FlowersEntities2 : DbContext
    {
        public FlowersEntities2()
            : base("name=FlowersEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TBL_ANNE> TBL_ANNE { get; set; }
        public DbSet<TBL_DG> TBL_DG { get; set; }
        public DbSet<TBL_KULLANICI> TBL_KULLANICI { get; set; }
        public DbSet<TBL_MUSTERI> TBL_MUSTERI { get; set; }
        public DbSet<TBL_SATISLAR> TBL_SATISLAR { get; set; }
        public DbSet<TBL_SEVGİLİ> TBL_SEVGİLİ { get; set; }
        public DbSet<TBL_WEDDING> TBL_WEDDING { get; set; }
        public DbSet<TBL_YENIIS> TBL_YENIIS { get; set; }
        public DbSet<TBL_YENIYIL> TBL_YENIYIL { get; set; }
    }
}
