//------------------------------------------------------------------------------
// <auto-generated>
//    Bu kod bir şablondan oluşturuldu.
//
//    Bu dosyada el ile yapılan değişiklikler uygulamanızda beklenmedik davranışa neden olabilir.
//    Kod yeniden oluşturulursa, bu dosyada el ile yapılan değişikliklerin üzerine yazılacak.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SATISLAR
    {
        public int SATISID { get; set; }
        public Nullable<int> FLOWER { get; set; }
        public Nullable<int> MUSTERI { get; set; }
        public Nullable<byte> ADET { get; set; }
        public Nullable<decimal> FIYAT { get; set; }
    
        public virtual TBL_ANNE TBL_ANNE { get; set; }
        public virtual TBL_DG TBL_DG { get; set; }
        public virtual TBL_MUSTERI TBL_MUSTERI { get; set; }
        public virtual TBL_SEVGİLİ TBL_SEVGİLİ { get; set; }
        public virtual TBL_WEDDING TBL_WEDDING { get; set; }
        public virtual TBL_YENIIS TBL_YENIIS { get; set; }
        public virtual TBL_YENIYIL TBL_YENIYIL { get; set; }
    }
}
